// <auto-generated />
namespace AngularandCSS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addition_of_email_confirmation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addition_of_email_confirmation));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210225424_addition_of_email_confirmation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
